### ISSUE TITLE
More reliable dirtiness checking

### ISSUE THREAD

**Issue by snoyberg** [urbanslug/yesod-devel#1]
My idea of how dirtiness checking would work was along these lines:
- User specifies a target module containing `main` (or some other named function)
- ide-backend builds that module and everything it depends on (by using the targets API)
- wai-devel finds all of the .hi files to determine the module files and external non-source files (like hamlet templates) that it needs to watch for rebuilding

If this works as I expect (which I could be wrong), you wouldn't need to have any list of known file extensions, wouldn't need to ignore the test directory, and will handle many use cases outside of Yesod's.

**Comment by urbanslug** [comment]
Hello @snoyberg please take a look at the latest commit.

**Comment by urbanslug** [comment]
@snoyberg You will find that this issue has been fixed. Please agree in a comment so that I may close it.

**Comment by snoyberg** [comment]
The master branch does not compile.

**Comment by snoyberg** [comment]
```
[7 of 9] Compiling Devel.ReverseProxy ( src/Devel/ReverseProxy.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Devel/ReverseProxy.o )

src/Devel/ReverseProxy.hs:29:1: parse error on input ‘<<<<<<<’

--  While building package wai-devel-0.1.0.0 using:
      /home/vagrant/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.8.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build lib:wai-devel exe:wai-devel --ghc-options -hpcdir .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
```

**Comment by urbanslug** [comment]
@snoyberg Fixed
Travis build still running but locally builds on 7.8.
Currently 7.10 build fails due to changes in the typechecker working on it.  
**UPDATE**
Builds on GHC 7.8 and 7.10
