### ISSUE TITLE
Can't find modules in `executable` part of cabal file

### ISSUE THREAD

**Issue by parsonsmatt** [urbanslug/yesod-devel#12]
For a reproduction, see the `exec-modules` branch in [this repository](https://github.com/parsonsmatt/wai-devel-repro/tree/exec-modules)

Attempting run `wai-devel -p app/Main.hs -f main` in the project has the following output:

``` bash
λ wai-devel -p app/Main.hs -f main
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
UpdateStatusDone
Error: app/Main.hs@5:8-5:12 Could not find module ‘Exec’
Use -v to see a list of the files searched for.
```

**Comment by urbanslug** [comment]
I have pushed a fix for issue 10 to 12.

**Comment by parsonsmatt** [comment]
I'm getting the following errors now:

```
λ wai-devel -p src/App.hs -f main
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
KindServerDied
```

with all of the projects I have on hand

**Comment by parsonsmatt** [comment]
With the hackage release, I'm getting the same errors as before on the three issues

**Comment by urbanslug** [comment]
Okay, I was sure I had these issues fixed over a week ago. Let me check it out.

**Comment by urbanslug** [comment]
This is what I have:

```
$ wai-devel -p app/Main.hs -f main
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
UpdateStatusProgress [1 of 2] Compiling Exec
UpdateStatusProgress [2 of 2] Compiling Main
UpdateStatusDone
Warning: app/Main.hs@18:28-18:32 Defaulting the following constraint(s) to type ‘Integer’
  (Integral a0)
    arising from a use of ‘asdf’
    at /home/urbanslug/src/haskell/wai-devel-repro/app/Main.hs:18:28-31
  (Read a0)
    arising from a use of ‘read’
    at /home/urbanslug/src/haskell/wai-devel-repro/app/Main.hs:18:35-38
  (Show a0)
    arising from a use of ‘show’
    at /home/urbanslug/src/haskell/wai-devel-repro/app/Main.hs:18:21-24
In the first argument of ‘(.)’, namely ‘asdf’
In the second argument of ‘(.)’, namely ‘asdf . read’
In the second argument of ‘(.)’, namely ‘show . asdf . read’
Setting phasers to stun... (port 1234) (ctrl-c to quit)

```

hmmm this is very unusual.

**Comment by parsonsmatt** [comment]
OK, I'm getting the same output as you now. I think that I forgot to run `stack build` before starting `wai-devel` which might have caused the problems.

Man, this package is _great_ -- the recompilation is nearly instantaneous :smile: Thanks so much for making it!

**Comment by urbanslug** [comment]
@snoyberg :point_up_2: :point_up: :point_up_2: 

@parsonsmatt Thanks, that means a lot.
