### ISSUE TITLE
Reload when load-time settings change

### ISSUE THREAD

**Issue by andrewthad** [urbanslug/yesod-devel#15]
If I have some type of configuration file for the application that is read at load time (not at compile time), I don't think that `wai-devel` has a way to reload when this file changes. One simple solution that would be sufficient for my use case would be to allow reloading the application in `wai-devel`. For example, maybe hitting the space bar could cause the application to be reloaded (but no recompilation would occur). This would be a useful feature.

**Comment by dbp** [comment]
As a more general solution, could we pass either directories or file extensions that should be watched in addition to `.hs` files? For example, my applications often have templates that are loaded at startup, and in development mode, I'd like the application to reload whenever those files change.

**Comment by andrewthad** [comment]
Yeah, that would probably be even better. It would let people who use `heist` would be better covered by `wai-devel` too.

**Comment by urbanslug** [comment]
@dbp You sent a PR to fix this, am I right? I'm closing this now.
