### ISSUE TITLE
Showing compile errors in browser

### ISSUE THREAD

**Issue by andrewthad** [urbanslug/yesod-devel#16]
Would it be possible to get the page that says "The application isn't built" to also show the compile time error if one occurred and is preventing a reload? This would be useful for when I make small changes that I don't expect to cause compile-time errors. Sometimes, they do cause errors, and it would be nice to have the browser notify me.

**Comment by urbanslug** [comment]
Yes, this is what it was doing a while back before we changed to that page because it seems "more interactive".

**Comment by andrewthad** [comment]
If it ever comes up for reconsideration, know that I am an example of someone who would prefer the other behavior. Thanks for letting me know why the decision was made.

**Comment by urbanslug** [comment]
Oh no, you shoudn't have closed this issue. This is a feature request and I will work on it and give feedback.

**Comment by urbanslug** [comment]
Fixed.
