### ISSUE TITLE
Language extension with "No" in front of them don't work

### ISSUE THREAD

**Issue by haBuu** [urbanslug/yesod-devel#2]
extractExtensions function in Compile.hs is not working correctly with e.g. NoImplicitPrelude extension. It gets parsed to "DisableExtension ImplicitPrelude" and then DisableExtension is thrown away and the extension becomes just -XImplicitPrelude. See https://hackage.haskell.org/package/Cabal-1.22.4.0/docs/Language-Haskell-Extension.html#t:Extension.

**Comment by urbanslug** [comment]
Thank you for your feedback. Sadly, I am currently working on issue #1. I will have to look at this later.

**Comment by urbanslug** [comment]
@haBuu You will find this issue has been taken care of. Please agree in a comment so that I may close it.

**Comment by haBuu** [comment]
Yes it works now.
