### ISSUE TITLE
Minor: Error: <no location info> module ‘Main’ is defined in multiple files:

### ISSUE THREAD

**Issue by gasi** [urbanslug/yesod-devel#21]
First of all, thanks for providing this tool.

Running `wai-devel --path Main.hs` prints the following error:

``` bash
Error: <no location info> module ‘Main’ is defined in multiple files: <path-to-project>/Main.hs
```

However, when I run  `wai-devel --path ./Main.hs` (note the `./` prefix) it doesn’t. Shouldn’t the first one work without error as well?

**Comment by urbanslug** [comment]
I reproduced this, I believe I know where this is coming from. I am working on this and should have it fixed soon. Sorry for the overly extended delay.

**Comment by gasi** [comment]
:+1:

**Comment by urbanslug** [comment]
I believe this is fixed.
