### ISSUE TITLE
No longer use the -p argument

### ISSUE THREAD

**Issue by yogsototh** [urbanslug/yesod-devel#23]
Apparently `wai-devel` doesn't use the `-p` or `--path` options.

After taking a quick look at the code, it looks like you only use `is-reverse-proxy`, `build-file`, `watch-directory`, `runFunction` and `version`.

**Comment by urbanslug** [comment]
@yogsototh I remember using it, will look at the code this weekend. I do remember using it unless a later commit overrode it.

**Comment by urbanslug** [comment]
I have checked and confirmed that `--path`/`-p` works.
