### ISSUE TITLE
README should have installation instructions

### ISSUE THREAD

**Issue by xrl** [urbanslug/yesod-devel#5]
Even if this isn't released/ready yet I'd like to give it a whirl. How can I get this going on my Mac OS X environment with these already installed?

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
```

```
$ stack --version
Version 0.1.3.1
```

```
$ cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
```

**Comment by urbanslug** [comment]
Hello, sorry for the late reply.

After cloning the repo you should run `stack build && stack install`.

A little more:
Currently, stack.yaml is a symlink to stack-7.8.yaml. You can switch this with a symlink stack-7.10 or with any other stack.yaml file you think would suit you best. However, it should be okay as is.

I will add this to the README right away.
