### ISSUE TITLE
wai-devel fails to find a custom entry point passed with '-p'

### ISSUE THREAD

**Issue by adinapoli** [urbanslug/yesod-devel#7]
Hello there,

I'm trying to use `wai-devel` for a Spock application. I have installed `wai-devel` and `backend-ide-server`, and my project structure looks like this:

```
.
├── LICENSE
├── Setup.hs
├── app
│   ├── Main.hs
│   └── Routes.hs
├── spock-test.cabal
├── src
│   └── Lib.hs
├── stack.yaml
└── test
    └── Spec.hs
```

If I run `wai-devel` with `wai-devel -p app/Main.hs` this is what I get:

```
☁  spock-test  wai-devel -p app/Main.hs
"app/Main.hs": openBinaryFile: does not exist (No such file or directory)
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
UpdateStatusDone
Error: <no location info> can't find file: /Users/adinapoli/programming/haskell/spock-test/Application.hs
```

What am I doing wrong? It doesn't work even with the fully qualified path:

```
☁  spock-test  wai-devel -p /Users/adinapoli/programming/haskell/spock-test/app/Main.hs
"/Users/adinapoli/programming/haskell/spock-test/app/Main.hs": openBinaryFile: does not exist (No such file or directory)
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
UpdateStatusDone
Error: <no location info> can't find file: /Users/adinapoli/programming/haskell/spock-test/Application.hs
```

My `PATH` and `GHC_PACKAGE_PATHS` were set with the following (because I have another build tool set as default on this work laptop I cannot uninstall):

```
export PATH=/Users/adinapoli/.stack/programs/x86_64-osx/ghc-7.10.2/bin:$PATH
export GHC_PACKAGE_PATH=$(stack path --local-pkg-db)
```

Thanks!
Alfredo

**Comment by urbanslug** [comment]
When you pass -p you should also pass -f unless in your -p ( file with the function you want to run) there is a `develMain` function. This however does not show in the error. It seems that in your case it doesn't look for `app/Main.hs` but rather looks for `Application.hs` let me look into it.

**Comment by urbanslug** [comment]
@adinapoli Thanks you really saved me there. There was a huge bug in the argument passing there that I hadn't noticed.

Try it now, I have pushed code that I believe fixes that. Remember that -p most often works with -f unless your -p argument contains a `develMain` function.

Waiting for your approval of the fix for me to close this issue.

**Comment by adinapoli** [comment]
Works great, thank you! I'm now getting a different error when it comes to resolving the modules in my main file, but that's a separate issue I will open:

```
☁  metrics [issue-2232] ⚡ wai-devel -p app/Main.hs -f main
"app/Main.hs"
"main"
Starting devel application at http://localhost:3000
UpdateStatusRequiredRestart
UpdateStatusDone
Error: app/Main.hs@6:8-6:19 Could not find module ‘Application’
Use -v to see a list of the files searched for.
```

Thank you for the quick response! You can close this.
